allow no authentication smtp email delivery
bngsudheer/ansible-role-redmine pull request #30
Opened 2020-10-15 08:32 UTC by pigay

2020-10-15 08:33 UTC, pigay commented on templates/home/redmine/redmine/config/configuration.yml.j2
> +    delivery_method: :smtp
"smtp" alone is not a valid option (https://www.redmine.org/projects/redmine/wiki/EmailConfiguration#delivery_method)

2020-10-20 15:15 UTC, bngsudheer reviewed
Why are we checking for != 'none'?

2020-10-20 21:16 UTC, pigay commented
It's just a keyword one can use to configure no authentication method.

Should I document this keyword in `README.md`?

2020-11-17 14:29 UTC, bngsudheer requested changes
I would do ```{% if redmine_smtp_settings_authentication %}```  instead of comparing to the string 'none'

2020-11-17 14:30 UTC, bngsudheer commented
Yes, please document the changes.

2020-11-17 19:01 UTC, pigay commented
Here it is.

2020-11-18 06:54 UTC, merged

2020-11-18 06:57 UTC, bngsudheer commented
Apparently, the tests broke

2020-11-18 08:28 UTC, pigay commented
Tests broke? Are they visible in github? I can't see the CI/CD.

What is the error?

2020-11-18 09:39 UTC, pigay commented
I tried to run the test on both `v2.1.1` and `v2.2.0` but it fails with this message:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not find the requested service firewalld: host"}
```
Maybe a problem with my version of ansible?

Anyway, what is the error that breaks the tests?